wikimedia-fonts (1.1) feisty; urgency=low   * Set fontconfig to use bitmap fonts upon install.  -- River Tarnell <river@wikimedia.org>  Sun, 13 May 2007 14:48:56 +0000
git-svn-id: file:///home/git-svn-mirror/pushmi-svn-mirror/trunk@22146 dd0e9695-b195-4be7-bd10-2dea1a65a6b6

diff --git a/debs/wikimedia-fonts/debian/postinst b/debs/wikimedia-fonts/debian/postinst
--- a/debs/wikimedia-fonts/debian/postinst
+++ b/debs/wikimedia-fonts/debian/postinst
@@ -23,11 +23,19 @@ set -e
 #DEBHELPER#
 
 if [ "$1" = configure -a -x /usr/bin/fc-cache ]; then
-       echo -n "Regenerating fonts cache... "
-       HOME=/root fc-cache -f -v 1>/var/log/fontconfig.log 2>&1 || \
-       (echo "failed; see /var/log/fontconfig.log for more information."; \
-        exit 1)
-       echo "done."
+    . /usr/share/debconf/confmodule
+    db_version 2.0 || true
+    db_set fontconfig/enable_bitmaps true || true
+    db_go || true
+
+    rm -f /etc/fonts/conf.d/70-no-bitmaps.conf
+    ln -fs /etc/fonts/conf.avail/70-yes-bitmaps.conf /etc/fonts/conf.d
+
+    echo -n "Regenerating fonts cache... "
+    HOME=/root fc-cache -fr -v 1>/var/log/fontconfig.log 2>&1 || \
+    (echo "failed; see /var/log/fontconfig.log for more information."; \
+     exit 1)
+    echo "done."
 fi
 
 exit 0
